### ISSUE TITLE
ctrl+z somehow causes me to go back to a previous tab?

### ISSUE THREAD

**Issue by Zireael07** [multiism/multi-medium#3]
In the demo, in addition to what it's supposed to do

**Comment by 1j01** [comment]
That's very strange. Normally browsers don't allow tabs to intercept keyboard shortcuts for switching tabs (Ctrl+Tab, Ctrl+Shift+Tab, Ctrl+PageDown, Ctrl+PageUp) except for Ctrl+1 through 9 which jumps to a specific tab. So if it was any of those previous shortcuts, I wouldn't expect the page to be able to respond to it in addition to the browser switching tabs. And JS code on a web page is not allowed to switch tabs.
My best guess would be a misconfigured browser extension, or AutoHotkey script, or something along those lines.
- Does this happen with any other sites?
- What browser are you using?
- Does it happen with all browser extensions disabled?

**Comment by Zireael07** [comment]
All right, I now checked and it happens on other tabs too, so probably not a multi-medium issue but a browser issue (Vivaldi)

Still probably worth it to preventDefault here

**Comment by Zireael07** [comment]
Looks like an undocumented feature of my browser (disabling all extensions doesn't change the behavior)

**Comment by 1j01** [comment]
So apparently Vivaldi [binds Ctrl+Z to reopening the last closed tab](https://forum.vivaldi.net/topic/69180/ctrl-z-shouldn-t-be-assigned-to-reopen-closed-tabs-opinion/8). It can be unbound in the settings, but it really shouldn't be bound in the first place. There's already Ctrl+Shift+T and other ways to reopen closed tabs.

I agree I should use preventDefault, and I think it should fix the issue. I've added it in https://github.com/multiism/multi-medium/commit/6d44aa58205dc863c5e9b382b49a742a4273c1ef
